name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: SDL2
      run: sudo apt install libsdl2-dev libsdl2-2.0-0 -y
    - name: make
      run: make
    - name: make cppcheck
      run: make cppcheck
