name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install SDL2
      run: sudo apt install libsdl2-dev libsdl2-2.0-0 -y
  
  syntax-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install cppcheck
      run: sudo apt install cppcheck
    - name: cppcheck logs
      run: make cppcheck
